# AI Firewall minifilter message protocol (shared user/kernel)

#pragma once

#define AISHIELD_MAGIC   0x48534641u  /* 'AFSH' */
#define AISHIELD_VERSION 1u

#define AISHIELD_CMD_SYNC_POLICY    1u
#define AISHIELD_CMD_PING           2u
#define AISHIELD_CMD_FILE_QUERY     3u
#define AISHIELD_CMD_FILE_RESPONSE  4u
#define AISHIELD_CMD_POLICY_ACK     5u

#define AISHIELD_POLICY_ALLOW 0u
#define AISHIELD_POLICY_BLOCK 1u
#define AISHIELD_POLICY_ASK   2u

#define AISHIELD_DECISION_ALLOW 0u
#define AISHIELD_DECISION_BLOCK 1u
#define AISHIELD_DECISION_ASK   2u

typedef struct _AISHIELD_MSG_HEADER {
    ULONG Magic;
    ULONG Version;
    ULONG Command;
    ULONG PayloadLength;
} AISHIELD_MSG_HEADER, *PAISHIELD_MSG_HEADER;

#define AISHIELD_MAX_PATH      520
#define AISHIELD_MAX_FOLDERS   32
#define AISHIELD_MAX_AI_PROCS  64
#define AISHIELD_MAX_APP_NAME  64

typedef struct _AISHIELD_FOLDER_ENTRY {
    WCHAR Path[AISHIELD_MAX_PATH];
    ULONG Policy;
} AISHIELD_FOLDER_ENTRY, *PAISHIELD_FOLDER_ENTRY;

typedef struct _AISHIELD_AI_PROC_ENTRY {
    ULONG Pid;
    WCHAR AppName[AISHIELD_MAX_APP_NAME];
} AISHIELD_AI_PROC_ENTRY, *PAISHIELD_AI_PROC_ENTRY;

typedef struct _AISHIELD_SYNC_PAYLOAD {
    ULONG GlobalPolicy;
    ULONG FolderCount;
    ULONG AiProcessCount;
    AISHIELD_FOLDER_ENTRY Folders[AISHIELD_MAX_FOLDERS];
    AISHIELD_AI_PROC_ENTRY AiProcesses[AISHIELD_MAX_AI_PROCS];
} AISHIELD_SYNC_PAYLOAD, *PAISHIELD_SYNC_PAYLOAD;

typedef struct _AISHIELD_FILE_QUERY {
    ULONG QueryId;
    ULONG Pid;
    WCHAR AppName[AISHIELD_MAX_APP_NAME];
    WCHAR Path[AISHIELD_MAX_PATH];
    ULONG FolderPolicy;
} AISHIELD_FILE_QUERY, *PAISHIELD_FILE_QUERY;

typedef struct _AISHIELD_FILE_RESPONSE {
    ULONG QueryId;
    ULONG Decision; /* AISHIELD_DECISION_* */
} AISHIELD_FILE_RESPONSE, *PAISHIELD_FILE_RESPONSE;

typedef struct _AISHIELD_POLICY_CACHE {
    AISHIELD_SYNC_PAYLOAD Sync;
    BOOLEAN ClientConnected;
    ULONG NextQueryId;
} AISHIELD_POLICY_CACHE, *PAISHIELD_POLICY_CACHE;
